Repository exercism/dart, pull requests merged in 2018-05, with the labels that each got.

#122 dart-exercism: Fix formatting and dependency issues
  exercises/armstrong-numbers/lib/example.dart
  pubspec.lock
Labels: bug

#116 New Exercise: Scrabble Score
  config.json
  exercises/scrabble-score/README.md
  exercises/scrabble-score/lib/example.dart
  exercises/scrabble-score/lib/scrabble_score.dart
  exercises/scrabble-score/pubspec.yaml
  exercises/scrabble-score/test/scrabble_score_test.dart
  test/exercises_test.dart
Labels: new-exercise

#118 phone-number: Update exercise using revised create_exercise tool
  exercises/phone-number/lib/example.dart
  exercises/phone-number/lib/phone_number.dart
  exercises/phone-number/pubspec.lock
  exercises/phone-number/pubspec.yaml
  exercises/phone-number/test/phone_number_test.dart
Labels: enhancement

#117 hello-world: Update exercise using revised create_exercise tool
  exercises/hello-world/pubspec.lock
  exercises/hello-world/test/hello_world_test.dart
Labels: enhancement

#119 gigasecond: Update exercise using revised create_exercise tool
  exercises/gigasecond/lib/example.dart
  exercises/gigasecond/pubspec.lock
  exercises/gigasecond/test/gigasecond_test.dart
Labels: enhancement

#121 bob: Add requirement to README to match tests
  exercises/bob/README.md
Labels: bug
