Repository exercism/dart, pull requests merged in 2018-08, with the labels that each got.

#145 Updated links to help resources
  config/exercise_readme.go.tmpl
  exercises/anagram/README.md
  exercises/armstrong-numbers/README.md
  exercises/bob/README.md
  exercises/difference-of-squares/README.md
  exercises/gigasecond/README.md
  exercises/hamming/README.md
  exercises/hello-world/README.md
  exercises/leap/README.md
  exercises/phone-number/README.md
  exercises/raindrops/README.md
  exercises/rna-transcription/README.md
  exercises/scrabble-score/README.md
  exercises/word-count/README.md
Labels: bug

#144 Add 'math' topic to relevant exercises in track config
  config.json
Labels: enhancement

#140 Provide non-empty description for Dart track.
  config.json
Labels: bug

#86 New Exercise: Acronym
  config.json
  exercises/acronym/README.md
  exercises/acronym/analysis_options.yaml
  exercises/acronym/lib/acronym.dart
  exercises/acronym/lib/example.dart
  exercises/acronym/pubspec.yaml
  exercises/acronym/test/acronym_test.dart
  pubspec.lock
Labels: low-priority, new-exercise
