Repository exercism/dart, pull requests merged in 2019-02, with the labels that each got.

#163 dart: Install link should point to SDK installation guide
  docs/INSTALLATION.md
Labels: update-document

#158 Update setup requirements in README
  README.md
Labels: update-document

#164 anagram: Revise exercise with updates to the specification
  exercises/anagram/test/anagram_test.dart
Labels: enhancement

#155 acronym: Revise exercise with updates to the specification
  exercises/acronym/README.md
  exercises/acronym/lib/example.dart
  exercises/acronym/test/acronym_test.dart
Labels: enhancement

#165 exercism/dart: Address Dart analyzer errors due to Dart 2.0 strong typing
  bin/create_exercise.dart
  test/exercises_test.dart
Labels: bug
