Repository exercism/dart, pull requests merged in 2019-10, with the labels that each got.

#203 Adds the 'Beer Song' exercise
  config.json
  exercises/beer-song/.meta/version
  exercises/beer-song/README.md
  exercises/beer-song/analysis_options.yaml
  exercises/beer-song/lib/beer_song.dart
  exercises/beer-song/lib/example.dart
  exercises/beer-song/pubspec.yaml
  exercises/beer-song/test/beer_song_test.dart
Labels: high-priority, new-exercise

#204 Create '.meta/version' file from canonical.json
  bin/create_exercise.dart
Labels: enhancement

#202 ♻refactor (config.json) Use new names for outdated topics
  config.json
Labels: bug

#211 Beer Song: Move version into pubspec.yml
  exercises/beer-song/.meta/version
  exercises/beer-song/pubspec.yaml
Labels: enhancement

#206 create_exercise: Check for the version in the proper file
  bin/create_exercise.dart
Labels: bug, high-priority
