Repository exercism/dart, pull requests merged in 2020-11, with the labels that each got.

#267 Moving from Travis to GitHub Actions
  .github/workflows/test.yml
  .travis.yml
  README.md
Labels: hacktoberfest-accepted

#272 collatz-conjecture: Update link to point to latest docs for package test
  exercises/collatz-conjecture/test/collatz_conjecture_test.dart
Labels: bug

#274 Remove version parameter all pubspec.yaml for exercises
  exercises/acronym/pubspec.yaml
  exercises/allergies/pubspec.yaml
  exercises/anagram/pubspec.yaml
  exercises/armstrong-numbers/pubspec.yaml
  exercises/beer-song/pubspec.yaml
  exercises/binary-search-tree/pubspec.yaml
  exercises/bob/pubspec.yaml
  exercises/difference-of-squares/pubspec.yaml
  exercises/gigasecond/pubspec.yaml
  exercises/hamming/pubspec.yaml
  exercises/hello-world/pubspec.yaml
  exercises/isbn-verifier/pubspec.yaml
  exercises/leap/pubspec.yaml
  exercises/pascals-triangle/pubspec.yaml
  exercises/phone-number/pubspec.yaml
  exercises/raindrops/pubspec.yaml
  exercises/resistor-color-duo/pubspec.yaml
  exercises/resistor-color/pubspec.yaml
  exercises/reverse-string/pubspec.yaml
  exercises/rna-transcription/pubspec.yaml
  exercises/robot-simulator/pubspec.yaml
  exercises/scrabble-score/pubspec.yaml
  exercises/space-age/pubspec.yaml
  exercises/two-fer/pubspec.yaml
  exercises/word-count/pubspec.yaml
Labels: enhancement
