Repository exercism/dart, pull requests merged in 2024-04, with the labels that each got.

#530 pubspec: Upgrade sdk constraints to Dart 3.2 as minimum
  .github/workflows/test.yml
  bin/create_exercise.dart
  exercises/concept/futures/pubspec.yaml
  exercises/concept/numbers/pubspec.yaml
  exercises/concept/strings/pubspec.yaml
  exercises/practice/acronym/pubspec.yaml
  exercises/practice/allergies/pubspec.yaml
  exercises/practice/anagram/pubspec.yaml
  exercises/practice/armstrong-numbers/pubspec.yaml
  exercises/practice/beer-song/pubspec.yaml
  exercises/practice/binary-search-tree/pubspec.yaml
  exercises/practice/bob/pubspec.yaml
  exercises/practice/collatz-conjecture/pubspec.yaml
  exercises/practice/darts/pubspec.yaml
  exercises/practice/diamond/pubspec.yaml
  exercises/practice/difference-of-squares/pubspec.yaml
  exercises/practice/forth/pubspec.yaml
  exercises/practice/gigasecond/pubspec.yaml
  exercises/practice/grains/pubspec.yaml
  exercises/practice/hamming/pubspec.yaml
  exercises/practice/hello-world/pubspec.yaml
  exercises/practice/high-scores/pubspec.yaml
  exercises/practice/isbn-verifier/pubspec.yaml
  exercises/practice/isogram/pubspec.yaml
  exercises/practice/leap/pubspec.yaml
  exercises/practice/luhn/pubspec.yaml
  exercises/practice/matching-brackets/pubspec.yaml
  exercises/practice/minesweeper/pubspec.yaml
  exercises/practice/nth-prime/pubspec.yaml
  exercises/practice/pangram/pubspec.yaml
  exercises/practice/pascals-triangle/pubspec.yaml
  exercises/practice/phone-number/pubspec.yaml
  exercises/practice/pig-latin/pubspec.yaml
  exercises/practice/prime-factors/pubspec.yaml
  exercises/practice/raindrops/pubspec.yaml
  exercises/practice/resistor-color-duo/pubspec.yaml
  exercises/practice/resistor-color/pubspec.yaml
  exercises/practice/reverse-string/pubspec.yaml
  exercises/practice/rna-transcription/pubspec.yaml
  exercises/practice/robot-simulator/pubspec.yaml
  exercises/practice/roman-numerals/pubspec.yaml
  exercises/practice/scrabble-score/pubspec.yaml
  exercises/practice/secret-handshake/pubspec.yaml
  exercises/practice/space-age/pubspec.yaml
  exercises/practice/sum-of-multiples/pubspec.yaml
  exercises/practice/triangle/pubspec.yaml
  exercises/practice/two-fer/pubspec.yaml
  exercises/practice/word-count/pubspec.yaml
  pubspec.lock
  pubspec.yaml
Labels: enhancement, x:action/improve, x:size/small

#544 zebra-puzzle: sync
  exercises/practice/zebra-puzzle/.docs/instructions.md
  exercises/practice/zebra-puzzle/.docs/introduction.md
Labels: x:size/tiny

#547 zebra-puzzle: sync
  exercises/practice/zebra-puzzle/.docs/introduction.md
Labels: x:size/tiny

#552 yacht: fix enum order
  exercises/practice/yacht/lib/categories.dart
Labels: x:rep/tiny

#555 Sync with recent probspec changes
  exercises/practice/all-your-base/.meta/config.json
  exercises/practice/binary-search/.meta/config.json
  exercises/practice/dnd-character/.meta/config.json
  exercises/practice/matching-brackets/.docs/instructions.md
  exercises/practice/matching-brackets/.docs/introduction.md
  exercises/practice/pig-latin/.docs/instructions.md
  exercises/practice/pig-latin/.docs/introduction.md
  exercises/practice/roman-numerals/.meta/tests.toml
  exercises/practice/roman-numerals/test/roman_numerals_test.dart
  exercises/practice/space-age/.docs/instructions.md
  exercises/practice/space-age/.docs/introduction.md
  exercises/practice/yacht/.docs/instructions.md
  exercises/practice/yacht/.docs/introduction.md
  exercises/practice/yacht/.meta/config.json
  exercises/practice/zebra-puzzle/.meta/config.json
Labels: x:rep/small
